### ISSUE TITLE
MELPA?

### ISSUE THREAD

**Issue by manuel-uberti** [jwiegley/git-undo-el#1]
Hi,

this not an _issue_, I am just curious: is there any plan to add this package to MELPA (or ELPA)? 

Thank you :)

**Comment by tzz** [comment]
...or GNU ELPA, or core Emacs... it's really useful!

**Comment by jwiegley** [comment]
I'm actually planning to just integrate it into Emacs itself.  Undoing in a region will happen if `C-x v u` is applied to an active region. Viewing the history of states, rather than a history of changes, will happen if `C-x v h` is given a prefix key.

**Comment by manuel-uberti** [comment]
Oh great, t!hanks

**Comment by tzz** [comment]
YES :) Thanks!
